/*
---------------------------------------------------------
DO NOT EDIT THIS FILE DIRECTLY

This file was built from components (CTEs)
found in more than one stored procedure.

build_record: NOTICE| 202401.08 | 09:26
---------------------------------------------------------
*/
delimiter $$
drop      procedure if exists before_01 $$
create    procedure before_01 () begin
with      cte00 (`cte00_time`) as (
          select    TIME(NOW())
          ),
          cte01 (`cte00_date`) as (
          select    DATE(NOW())
          )
select    cte00.*,
          cte01.*
from      cte00
join      cte01;

end $$
delimiter ;
