/*
---------------------------------------------------------
DO NOT EDIT THIS FILE DIRECTLY

This file was built from components (CTEs)
found in more than one stored procedure.

build_record: NOTICE| 202401.08 | 09:28
---------------------------------------------------------
*/
delimiter $$
DROP      PROCEDURE IF EXISTS before_01 $$
CREATE    PROCEDURE before_01 () begin
WITH      cte00 (`cte00_time`) AS (
          SELECT    TIME(NOW())
          ),
          cte01 (`cte00_date`) AS (
          SELECT    DATE(NOW())
          )
SELECT    cte00.*,
          cte01.*
FROM      cte00
JOIN      cte01;
END $$
delimiter ;
